version: "3"

services:
    php:
        build: docker/php
        container_name: bdr.docker
        restart: always
        command: "/data/php-apache.sh"
        volumes:
            - .:/var/www/bdr
            - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php:/data
        ports:
            - "80:80"
        environment:
            - APACHE_LOG_DIR=/var/log/apache2
        working_dir: /var/www/bdr
        links:
            - mysqldb

    mysqldb:
        image: mysql:5.5
        container_name: mysql.docker
        restart: always
        volumes:
            - "./docker/mysql/lib:/var/lib/mysql"
        environment:
            - MYSQL_DATABASE=bdr
            - MYSQL_ROOT_PASSWORD=docker
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=docker
        ports:
            - "3306:3306"